package com.dhhe.blog.persistent.dto;

public class BlogLabelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.blog_id
     *
     * @mbg.generated
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_label.label_id
     *
     * @mbg.generated
     */
    private String labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.blog_id
     *
     * @return the value of blog_label.blog_id
     *
     * @mbg.generated
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.blog_id
     *
     * @param blogId the value for blog_label.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_label.label_id
     *
     * @return the value of blog_label.label_id
     *
     * @mbg.generated
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_label.label_id
     *
     * @param labelId the value for blog_label.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId == null ? null : labelId.trim();
    }
}