package com.dhhe.blog.persistent.dto;

public class TempUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_user.ip_addr
     *
     * @mbg.generated
     */
    private String ipAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_user.id
     *
     * @return the value of temp_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_user.id
     *
     * @param id the value for temp_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_user.email
     *
     * @return the value of temp_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_user.email
     *
     * @param email the value for temp_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_user.ip_addr
     *
     * @return the value of temp_user.ip_addr
     *
     * @mbg.generated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_user.ip_addr
     *
     * @param ipAddr the value for temp_user.ip_addr
     *
     * @mbg.generated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }
}