package com.dhhe.blog.persistent.dao;

import com.dhhe.blog.persistent.dto.BlogLabelExample;
import com.dhhe.blog.persistent.dto.BlogLabelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    long countByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int deleteByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BlogLabelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int insert(BlogLabelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int insertSelective(BlogLabelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    List<BlogLabelKey> selectByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogLabelKey record, @Param("example") BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_label
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogLabelKey record, @Param("example") BlogLabelExample example);
}