package com.dhhe.blog.persistent.dao;

import com.dhhe.blog.persistent.dto.TempUser;
import com.dhhe.blog.persistent.dto.TempUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    long countByExample(TempUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int deleteByExample(TempUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int insert(TempUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int insertSelective(TempUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    List<TempUser> selectByExample(TempUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    TempUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TempUser record, @Param("example") TempUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TempUser record, @Param("example") TempUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempUser record);
}