spring:
  datasource:
    #DruidDataSource 所需参数
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://180.76.51.119:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialSize: 3
    minIdle: 3
    maxActive: 30
    maxWait: 15000
    timeBetweenEvictionRunsMillis: 120000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    removeAbandonedTimeoutMillis: 20000
    logAbandoned: true
    logDifferentThread: true
    filters: log4j,stat
    connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
    useGlobalDataSourceStat: true
    # Druid 监控 Servlet 配置参数
    druidRegistrationUrl: /druid/*
    resetEnable: true
    loginUsername: druid
    loginPassword: 123456
    # Druid 监控过滤相关配置参数
    filtersUrlPatterns: /*
    exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
    sessionStatMaxCount: 2000
    sessionStatEnable: true
    principalSessionName: session_user_key
    profileEnable: true
  security:
    user:
      name: admin
      password: 123456
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
mybatis:
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/**/*Mapper.xml
  type-aliases-package: com.dhhe.blog.persistent.dto

logging.config: classpath:logback-spring.xml
logging.path: E:/logs
server:
  servlet:
    context-path: /
application:
  login-page: /login
  system:
    name: blog
    author: hedonliberty@163.com
    version: 1.0.0
  interceptor:
      exclusions: /index,/,/login,/user/login,/css/**,/img/**,/js/**,/thirdpart/**
